### ISSUE TITLE
Pip install

### ISSUE THREAD

**Issue by SenWu** [HazyResearch/metal#29]
Can you add all dependencies when pip install? A reference: https://github.com/HazyResearch/fonduer/blob/master/setup.py#L11-L30

**Comment by ajratner** [comment]
Good idea, thanks!

**Comment by bhancock8** [comment]
Fixed by #32, though it turns out that including matplotlib in your dependencies is a bit of a bear (https://stackoverflow.com/questions/34977388/matplotlib-runtimeerror-python-is-not-installed-as-a-framework). Got around it eventually, but consider yourself lucky @SenWu that Fonduer doesn't use matplotlib!
