### ISSUE TITLE
metric_score function should require pos_label value passed in

### ISSUE THREAD

**Issue by ljx1110** [HazyResearch/metal#47]
When I test Basics tutorial case, realize metric value reported by "score" function is not right. precision_score, recall_score and f1_score functions have "pos_label" argument set to 1 by default. In this case, labels passed in score function are composite of 1 and 2. pos_label should be set to 2 in this case. Otherwise, metric is calculated by mistake. 

Regarding to MajorityLabelVoter, predict_prob could be sum(label_function_output) / total_label_function_count. This will generate probabilistic label. If k = 2, it could be continuous value in the range of [0, 1] instead of 0 or 1. This is to compare against Metal predict_prob values if draw AUC curves. Rank over labels are more useful than a single set of precision/recall/f1 score which assume a hard threshold of probability (it's 0.5 when k = 2).

**Comment by ajratner** [comment]
Hi @ljx1110 ,

I'm not sure I totally understand the issue?  First of all, what do you mean by "composite of 1 and 2"?  Perhaps you could show me an example where you think the score is off?  You can always change `pos_label` if you want to have 1 mean positive and 2 mean negative, if that's the issue?  Otherwise I think the score function should be working fine

As for `MajorityLabelVoter`, we don't output probabilistic labels here- the full probability mass is put on the majority label (as per the docstring).  Overall however, we could definitely add in other metric reports like AUC curves and rank-based metrics for higher cardinality settings!

**Comment by ljx1110** [comment]
Hi Alex,

   Sorry for the confusion. Let me clarify. 

  When we test Snorkel, our LF output is -1, 0 and 1. In our earlier discussion. To use Metal, I need to transit LF output from -1 -> 1 and 1 -> 2 . So, "1" means negative and "2" means positive. 

   In metric_score function, it doesn't pass in pos_label value. predict_score/recall_score/f1_score are always using default pos_label value as 1. In Basics case in tutorial, Ls[1] and Ys[1] are 1s and 2s. You assume 1 as pos_label, right?

   `label_model.score(Ls[1], Ys[1], metric=['precision', 'recall', 'f1'])` ->
   `metric_score(Y, Y_p, metric, ignore_in_gold=[0])` ->
   `precision_score(gold, pred, pos_label=1, ignore_in_gold=[], ignore_in_pred=[])`

   I did manually set pos_label value to 2 for each metric function in our case. 

   What I mean is "score" function doesn't have pos_label variable exposed in the interface. It may be more convenient to add it and allow user to adjust it.

   Please let me know if my understanding is wrong.

**Comment by astarostap** [comment]
Just corroborating that I also had to write a method to translate labels to Metal language (1 for pos / 2 for neg) for my experiments and would be nice to avoid doing that

**Comment by brahmaneya** [comment]
Active development is being moved to our main repo, https://github.com/snorkel-team/snorkel, where we use a different labeling convention (-1 for abstain, and 0...k-1 for actual labels).
